name: "Deploy to QuantCDN"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Cache local revision file
        id: cache-quant-revisions
        uses: actions/cache@v4
        with:
          path: .quant-revision
          key: quant-revision

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build static output
        run: npm run generate

      - name: Deploy updates to QuantCDN
        uses: quantcdn/deploy-action@v5.0.0
        with:
          customer: ${{ vars.QUANT_CUSTOMER }}
          project: ${{ vars.QUANT_PROJECT }}
          token: ${{ secrets.QUANT_TOKEN }}
          endpoint: ${{ vars.QUANT_ENDPOINT || 'https://api.quantcdn.io/v1' }}
          dir: .output/public
          chunk-size: 20
          skip-purge: true

      - name: Purge the QuantCDN cache
        uses: quantcdn/purge-action@v2
        with:
          customer: ${{ vars.QUANT_CUSTOMER }}
          project: ${{ vars.QUANT_PROJECT }}
          token: ${{ secrets.QUANT_TOKEN }}
          endpoint: ${{ vars.QUANT_ENDPOINT || 'https://api.quantcdn.io/v1' }}
          url_pattern: "/*"
